name: 'Terraform Deploy'

on:
  push:
    branches:
        - main
        - dgracili
env:
  AWS_REGION: 'us-east-1'
  TF_VERSION: '1.13.1'
  WORKING_DIRECTORY: 'infra'
  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4


      #Configure terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
       
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      working-directory:  ${{ env.WORKING_DIRECTORY }}

      #Validate IaC in terraform
    - name: Terraform Format
      id: format
      run: terraform fmt -recursive
      working-directory:  ${{ env.WORKING_DIRECTORY }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory:  ${{ env.WORKING_DIRECTORY }}
    
      #Validate static code in IaC
    - name: Checkov Scan
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: . 
        framework: terraform
        soft_fail: true  
        output_format: json 
        output_file_path: checkov_results.json
    
    # - name: Check for Critical Findings
    #   id: check_critical
    #   run: |
    #     critical_count=$(jq '.results.failed_checks | map(select(.severity=="CRITICAL")) | length' checkov_results.json)
    #     high_count=$(jq '.results.failed_checks | map(select(.severity=="HIGH")) | length' checkov_results.json)
          
    #     echo "Vulnerabilidades críticas: $critical_count"
    #     echo "Vulnerabilidades altas: $high_count"

    #     if [[ $critical_count -gt 0 || $high_count -gt 0 ]]; then
    #       echo "::error::Se encontraron vulnerabilidades CRÍTICAS o ALTAS. Deteniendo el despliegue."
    #       exit 1
    #     fi
    #   shell: bash
      env:
        ACTIONS_STEP_DEBUG: true


    - name: Terraform Plan
      id: plan
      #run: terraform plan -no-color -out=tfplan -var-file=tfvars/terraform-dev.tfvars
      run: terraform plan -no-color -out=tfplan -var-file=tfvars/terraform-dev.tfvars
      working-directory: ${{ env.WORKING_DIRECTORY }}

    # - name: Terraform Apply
    #   id: apply
    #   run: terraform apply -var-file=tfvars/terraform-dev.tfvars --auto-approve tfplan 
    #   working-directory:  ${{ env.WORKING_DIRECTORY }}
    # - name: Terraform Destroy
    #   id: destroy
    #   if: github.ref == 'refs/heads/destroy-env' && github.event_name == 'push'
    #   run: terraform destroy -auto-approve -var-file=tfvars/terraform-dev.tfvars tfplan 
    #   working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Conditional Terraform Apply or Destroy
      id: apply_or_destroy
      run: |
          DESTROY_FLAG=$(jq -r '.destroy_infrastructure' tfvars/vars.json)
          if [[  "$DESTROY_FLAG" == "true" ]]; then
            echo "Variable 'destroy_infrastructure' es 'true'. running 'terraform destroy'."
            terraform destroy -var-file=tfvars/terraform-dev.tfvars -auto-approve
          else
            echo "Variable 'destroy_infrastructure' es 'false'. running 'terraform apply'."
            terraform apply -var-file=tfvars/terraform-dev.tfvars -auto-approve tfplan 
          fi
      working-directory: ${{ env.WORKING_DIRECTORY }}